In [ ]:
# What is Pandas?
# Python library used for working with structured data sets (tables). It has functions for analyzing, cleaning, exploring, and manipulating data. Similar to data tables in SQL and Excel.

In [2]:
# install pandas

In [3]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\sa776\appdata\local\programs\python\python314\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in c:\users\sa776\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sa776\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\sa776\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\sa776\appdata\local\programs\python\python314\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
# import pandas
import pandas as pd

In [5]:
pd.__version__ # check installed pandas version

'3.0.2'

In [ ]:
# What is Dataframe?
# It's a structured data constructed with rows and columns, similar to a SQL tables or Excel tables

In [6]:
# 1 Create Dataframe

In [7]:
# using a List
df = pd.DataFrame([11,22,33], columns=['Col_Name'])
print(df)

   Col_Name
0        11
1        22
2        33

In [8]:
print(type(df)) # check data type

<class 'pandas.DataFrame'>

In [9]:
# using Dictionary of Lists
data = {
    'Name': ['Madhav', 'Vishakha', 'Lalita', 'Rishabh'],
    'Age': [16,17,18,19],
    'Salary': [90000, 70000, 50000, 30000]
}

In [10]:
df = pd.DataFrame(data)
print(df)

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000
2    Lalita   18   50000
3   Rishabh   19   30000

In [11]:
print(type(df))

<class 'pandas.DataFrame'>

In [12]:
 # 2 Basic Dataframe Understanding

In [13]:
df.head(2) # top rows

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000

In [14]:
df.tail(2) # last rows

      Name  Age  Salary
2   Lalita   18   50000
3  Rishabh   19   30000

In [15]:
df.shape # returns a tuple containing the shape of the DataFrame - rows & columns

(4, 3)

In [16]:
df.columns # list of column names in a dataframe

Index(['Name', 'Age', 'Salary'], dtype='str')

In [17]:
df.rename(columns={'Salary': 'Monthly_Salary'}, inplace=True) # rename column name/s

In [18]:
df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [19]:
df.info()  # info method prints information about the DataFrame

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [20]:
df.describe() # describe method generates descriptive statistics of DataFrame, only for numerical-value columns

             Age  Monthly_Salary
count   4.000000        4.000000
mean   17.500000    60000.000000
std     1.290994    25819.888975
min    16.000000    30000.000000
25%    16.750000    45000.000000
50%    17.500000    60000.000000
75%    18.250000    75000.000000
max    19.000000    90000.000000

In [21]:
# 3 Save and Load data from csv

In [25]:
df.to_csv('Test_data.csv', index=False) # export data frame

In [27]:
load_df = pd.read_csv('Test_data.csv') # import dataframe
load_df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [28]:
# 4. Rows and Columns - Selection

In [31]:
# select column
df[['Name']]  # single column
df[['Name', 'Monthly_Salary']]

       Name  Monthly_Salary
0    Madhav           90000
1  Vishakha           70000
2    Lalita           50000
3   Rishabh           30000

In [39]:
 # select rows
# loc - index name based
df.loc[df.Name == 'Madhav']
df.loc[(df.Name=='Madhav') & (df.Monthly_Salary>=50000)]

     Name  Age  Monthly_Salary
0  Madhav   16           90000

In [40]:
df.loc[0:2]

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000

In [41]:
# iloc - index-value based
# df.iloc[0]
df.iloc[0:2] # [start:stop:step]

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000

In [42]:
# 5. Filter dataframe

In [43]:
df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [47]:
df['Age'] > 15

0    True
1    True
2    True
3    True
Name: Age, dtype: bool

In [49]:
df_age_filter = df[df['Age'] >=18]

In [50]:
df_age_filter

      Name  Age  Monthly_Salary
2   Lalita   18           50000
3  Rishabh   19           30000

In [51]:
df[(df['Age'] >= 18) & (df['Monthly_Salary'] >= 50000)]

     Name  Age  Monthly_Salary
2  Lalita   18           50000

In [52]:
df.where(df['Age'] >= 18)

      Name   Age  Monthly_Salary
0      NaN   NaN             NaN
1      NaN   NaN             NaN
2   Lalita  18.0         50000.0
3  Rishabh  19.0         30000.0

In [53]:
df.where(df['Age'] >= 18, other = 'Not Eligible')

           Name           Age Monthly_Salary
0  Not Eligible  Not Eligible   Not Eligible
1  Not Eligible  Not Eligible   Not Eligible
2        Lalita            18          50000
3       Rishabh            19          30000

In [1]:
import pandas as pd

In [10]:
# 6. Rows and Columns - Operation (Add, Update, Delete)

In [4]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\sa776\appdata\local\programs\python\python314\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in c:\users\sa776\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sa776\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\sa776\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\sa776\appdata\local\programs\python\python314\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd

In [7]:
data = {
    'Name': ['Madhav', 'Vishakha', 'Lalita', 'Rishabh'],
    'Age': [16,17,18,19],
    'Salary': [90000, 70000, 50000, 30000]
}

In [8]:
df = pd.DataFrame(data)
print(df)

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000
2    Lalita   18   50000
3   Rishabh   19   30000

In [9]:
df

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000
2    Lalita   18   50000
3   Rishabh   19   30000

In [12]:
# add new column
df['Team'] = ['CEO', 'HR', 'CTO', 'DA']
df

       Name  Age  Salary Team
0    Madhav   16   90000  CEO
1  Vishakha   17   70000   HR
2    Lalita   18   50000  CTO
3   Rishabh   19   30000   DA

In [14]:
df['Bonus'] = df['Salary'] * 0.2
df

       Name  Age  Salary Team    Bonus
0    Madhav   16   90000  CEO  18000.0
1  Vishakha   17   70000   HR  14000.0
2    Lalita   18   50000  CTO  10000.0
3   Rishabh   19   30000   DA   6000.0

In [16]:
# add new row
df.loc[len(df)] = ['Ayush', 20, 95000, 'IT', 20000]
df

       Name  Age  Salary Team    Bonus
0    Madhav   16   90000  CEO  18000.0
1  Vishakha   17   70000   HR  14000.0
2    Lalita   18   50000  CTO  10000.0
3   Rishabh   19   30000   DA   6000.0
4     Ayush   20   95000   IT  20000.0

In [17]:
len(df)

5

In [19]:
# Update value - using index name
df.loc[0, 'Salary'] = 85000
df

       Name  Age  Salary Team    Bonus
0    Madhav   16   85000  CEO  18000.0
1  Vishakha   17   70000   HR  14000.0
2    Lalita   18   50000  CTO  10000.0
3   Rishabh   19   30000   DA   6000.0
4     Ayush   20   95000   IT  20000.0

In [20]:
# Update value - using column value
df.loc[df.Name == 'Madhav', 'Salary'] = 90000
df

       Name  Age  Salary Team    Bonus
0    Madhav   16   90000  CEO  18000.0
1  Vishakha   17   70000   HR  14000.0
2    Lalita   18   50000  CTO  10000.0
3   Rishabh   19   30000   DA   6000.0
4     Ayush   20   95000   IT  20000.0

In [21]:
# delete value - row and column values

In [25]:
df = df.drop(df[df.Name == 'Lalita'].index) #drop row, axis =0

In [34]:
df.drop('Age', axis=1, inplace=True)  # drop column

In [35]:
df

       Name  Salary Team
0    Madhav   90000  CEO
1  Vishakha   70000   HR
3   Rishabh   30000   DA
4     Ayush   95000   IT

In [36]:
# df.drop(['Name', 'Team'], axis=1) # delete multiple columns

In [37]:
df

       Name  Salary Team
0    Madhav   90000  CEO
1  Vishakha   70000   HR
3   Rishabh   30000   DA
4     Ayush   95000   IT

In [38]:
# Sort value
df.sort_values('Salary') # ascending order, by default

       Name  Salary Team
3   Rishabh   30000   DA
1  Vishakha   70000   HR
0    Madhav   90000  CEO
4     Ayush   95000   IT

In [39]:
df.sort_values('Salary', ascending=False) # descending order

       Name  Salary Team
4     Ayush   95000   IT
0    Madhav   90000  CEO
1  Vishakha   70000   HR
3   Rishabh   30000   DA

In [40]:
# 7. Working with date value

In [42]:
df['DOJ'] = ['2026-01-01', '2026-01-15', '2026-03-28', '2026-06-01']
df

       Name  Salary Team         DOJ
0    Madhav   90000  CEO  2026-01-01
1  Vishakha   70000   HR  2026-01-15
3   Rishabh   30000   DA  2026-03-28
4     Ayush   95000   IT  2026-06-01

In [44]:
df['DOJ'].dtype

In [45]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [46]:
df['DOJ'].dtype

dtype('<M8[us]')

In [48]:
df['DOJ'].dt.year

0    2026
1    2026
3    2026
4    2026
Name: DOJ, dtype: int32

In [49]:
# extract year, month, week, day
df['DOJ'].dt.year
df['DOJ'].dt.month
df['DOJ'].dt.month
df['DOJ'].dt.day_name()

0    Thursday
1    Thursday
3    Saturday
4      Monday
Name: DOJ, dtype: str

In [51]:
df['DOJ'] + pd.Timedelta(days=90) # no. of days adding , subtracting

0   2026-04-01
1   2026-04-15
3   2026-06-26
4   2026-08-30
Name: DOJ, dtype: datetime64[us]

In [52]:
df

       Name  Salary Team        DOJ
0    Madhav   90000  CEO 2026-01-01
1  Vishakha   70000   HR 2026-01-15
3   Rishabh   30000   DA 2026-03-28
4     Ayush   95000   IT 2026-06-01

In [53]:
# 8. Handling missing values

In [54]:
df

       Name  Salary Team        DOJ
0    Madhav   90000  CEO 2026-01-01
1  Vishakha   70000   HR 2026-01-15
3   Rishabh   30000   DA 2026-03-28
4     Ayush   95000   IT 2026-06-01

In [55]:
df.isnull()

    Name  Salary   Team    DOJ
0  False   False  False  False
1  False   False  False  False
3  False   False  False  False
4  False   False  False  False

In [1]:
import pandas as pd

In [4]:
data = {
    'Name': ['Madhav', 'Vishakha', 'Lalita', 'Rishabh'],
    'Age': [16,17,18,19],
    'Salary': [90000, 70000, 50000, 30000]
}

In [5]:
df = pd.DataFrame(data)
print(df)

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000
2    Lalita   18   50000
3   Rishabh   19   30000

In [6]:
df['Bonus'] = df['Salary'] * 0.2
df

       Name  Age  Salary    Bonus
0    Madhav   16   90000  18000.0
1  Vishakha   17   70000  14000.0
2    Lalita   18   50000  10000.0
3   Rishabh   19   30000   6000.0

In [8]:
df.loc[len(df)] = ['Ayush', 20, 95000,  20000]
df

       Name  Age  Salary    Bonus
0    Madhav   16   90000  18000.0
1  Vishakha   17   70000  14000.0
2    Lalita   18   50000  10000.0
3   Rishabh   19   30000   6000.0
4     Ayush   20   95000  20000.0

In [10]:
df['DOJ'] = ['2026-01-01', '2026-01-15', '2026-03-28', '2026-04-21',  '2026-06-01']
df

       Name  Age  Salary    Bonus         DOJ
0    Madhav   16   90000  18000.0  2026-01-01
1  Vishakha   17   70000  14000.0  2026-01-15
2    Lalita   18   50000  10000.0  2026-03-28
3   Rishabh   19   30000   6000.0  2026-04-21
4     Ayush   20   95000  20000.0  2026-06-01

In [11]:
import numpy as np

In [12]:
df.loc[df.Name=='Rishabh', 'Salary'] = np.nan

In [13]:
df

       Name  Age   Salary    Bonus         DOJ
0    Madhav   16  90000.0  18000.0  2026-01-01
1  Vishakha   17  70000.0  14000.0  2026-01-15
2    Lalita   18  50000.0  10000.0  2026-03-28
3   Rishabh   19      NaN   6000.0  2026-04-21
4     Ayush   20  95000.0  20000.0  2026-06-01

In [14]:
df.isnull()

    Name    Age  Salary  Bonus    DOJ
0  False  False   False  False  False
1  False  False   False  False  False
2  False  False   False  False  False
3  False  False    True  False  False
4  False  False   False  False  False

In [15]:
df.isnull().sum()

Name      0
Age       0
Salary    1
Bonus     0
DOJ       0
dtype: int64

In [16]:
df.fillna(4000)

       Name  Age   Salary    Bonus         DOJ
0    Madhav   16  90000.0  18000.0  2026-01-01
1  Vishakha   17  70000.0  14000.0  2026-01-15
2    Lalita   18  50000.0  10000.0  2026-03-28
3   Rishabh   19   4000.0   6000.0  2026-04-21
4     Ayush   20  95000.0  20000.0  2026-06-01

In [20]:
df['Team'] = ['CEO', 'HR', 'CTO', 'DA', 'IT']
df

       Name  Age   Salary    Bonus         DOJ Team
0    Madhav   16  90000.0  18000.0  2026-01-01  CEO
1  Vishakha   17  70000.0  14000.0  2026-01-15   HR
2    Lalita   18  50000.0  10000.0  2026-03-28  CTO
3   Rishabh   19      NaN   6000.0  2026-04-21   DA
4     Ayush   20  95000.0  20000.0  2026-06-01   IT

In [17]:
# 9. Aggregation and group by

In [21]:
df['Team'].value_counts()

Team
CEO    1
HR     1
CTO    1
DA     1
IT     1
Name: count, dtype: int64

In [27]:
df[df['Team'] =='HR'].value_counts() # frequency of values in Team column

Name      Age  Salary   Bonus    DOJ         Team
Vishakha  17   70000.0  14000.0  2026-01-15  HR      1
Name: count, dtype: int64

In [25]:
df.groupby('Team')['Salary'].sum()  # aggregation based on group by

Team
CEO    90000.0
CTO    50000.0
DA         0.0
HR     70000.0
IT     95000.0
Name: Salary, dtype: float64

In [26]:
df.groupby('Team').agg({'Salary': 'mean', 'Name': 'count'})

       Salary  Name
Team
CEO   90000.0     1
CTO   50000.0     1
DA        NaN     1
HR    70000.0     1
IT    95000.0     1

In [28]:
# 10. Concatenate and Merge Dataframe(JOINS)

In [29]:
df1 = pd.DataFrame({'ID':[1,2,3], 'Name':['A', 'B', 'C']})
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [30]:
df2 = pd.DataFrame({'ID':[1,2,2,4], 'Score':[88,96,77,79]})
df2

   ID  Score
0   1     88
1   2     96
2   2     77
3   4     79

In [33]:
pd.concat([df1, df2], axis=0) # vertical / row level / top on top

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   2  NaN   77.0
3   4  NaN   79.0

In [34]:
pd.concat([df1, df2], axis=1) # horizontal / column level / side on side

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   2     77
3  NaN  NaN   4     79

In [35]:
# merge = join

In [36]:
pd.merge(df1, df2, how='inner', on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [37]:
pd.merge(df1, df2, how='inner', left_on='ID', right_on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [38]:
# 11. AI and ChatGPT

In [39]:
df

       Name  Age   Salary    Bonus         DOJ Team
0    Madhav   16  90000.0  18000.0  2026-01-01  CEO
1  Vishakha   17  70000.0  14000.0  2026-01-15   HR
2    Lalita   18  50000.0  10000.0  2026-03-28  CTO
3   Rishabh   19      NaN   6000.0  2026-04-21   DA
4     Ayush   20  95000.0  20000.0  2026-06-01   IT

In [40]:
# Prompt to filter salary > 70000 and January employees

In [ ]:
# Method-1: basic filter
df[(df['Month'] == 1) & (df['Salary'] >= 70000)]

In [ ]:
# Method-2: query method
df.query("Month == 1 and Salary >= 70000")